import "bootstrap-icons/font/bootstrap-icons.css";
import type { Metadata } from "next";
import "@fontsource/space-mono"; // Import the correct package for the Space Mono font from Google Fonts
import "./globals.css";
import Sidebar from "./components/Sidebar";


const space = "Space Mono"; // Update the variable to use the correct font name

export const metadata: Metadata = {
  title: "J0b B0b",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 

  return (
    <html lang="en">
      <body className={space.className}>
        <div className="flex bg-beige">
          <div className="hidden lg:grid">
            <Sidebar/>
          </div>
          <main className="layout__main-content p-12 min-h-screen">{children}</main>
        </div>
      </body>
    </html>
  );
}
function useState(arg0: boolean): [any, any] {
  throw new Error("Function not implemented.");
}

